### ISSUE TITLE
Deep recursion on 5.24

### ISSUE THREAD

**Issue by nullfieldio** [Camspi/XML-Simple-Sugar#1]
`Deep recursion on subroutine "XML::Simple::Sugar::AUTOLOAD" at (eval 1554) line 237, <DATA> line 1.`
`Deep recursion on subroutine "XML::Simple::Sugar::xml_subnode" at (eval 1555) line 5, <DATA> line 1.`
`Deep recursion on subroutine "XML::Simple::Sugar::new" at perl/lib/site_perl/5.24.1/XML/Simple/Sugar.pm line 258, <DATA> line 1.`

**Comment by Camspi** [comment]
Resolved in commit 9f13aab9c6ba9a3554515c5d47bda25a056ec5ef and https://metacpan.org/release/CAMSPI/XML-Simple-Sugar-v1.1.1

**Comment by nullfieldio** [comment]
Speedy! Thank you

**Comment by Camspi** [comment]
😃
